services:
  api:
    container_name: api
    networks:
      - myNetwork
    restart: always
    build:
      context: .
    volumes:
      - ./.env:/opt/api/.env
    ports:
      - 3000:${DEV_PORT}
    depends_on:
      - db
  db:
    image: postgres
    container_name: database
    networks:
      - myNetwork
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DATABASE_PORT}:5432"


networks:
  myNetwork:
    driver: bridge
volumes:
  db_data: